---
- hosts: "linux05"
  become: true
  tasks:
    - name: instalamos apache
      package:
        name: httpd
        state: latest
      tags: install
    - name: levantar servicio httpd y dejarlo persistente
      service:
        name: httpd
        state: started
        enabled: yes
      tags: config
    - name: creamos index.html
      file:
        path: /var/www/html/index.html
        state: touch
      tags: config
    - name: añadir linea al index.html
      copy:
        content: "Hello world"
        dest: /var/www/html/index.html
      tags: config
    - name: desinstalar apache
      package:
        name: httpd
        state: absent
      tags: never,uninstall